### ISSUE TITLE
lots of latex warnings and issues

### ISSUE THREAD

**Issue by davidwhogg** [aimalz/prob-z#1]
"""
Class revtex4-1 Warning: Assuming \noaffiliation for authors.

[1{/usr/local/texlive/2013/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
<real-prior-samps.png, id=24, 578.16pt x 433.62pt> <use real-prior-samps.png>
<rando-lik-samps.png, id=26, 578.16pt x 433.62pt> <use rando-lik-samps.png>
[2 <./real-prior-samps.png>] <inputs.png, id=34, 578.16pt x 433.62pt>
<use inputs.png>

LaTeX Warning: Reference `fig:results' on page 3 undefined on input line 154.

[3 <./rando-lik-samps.png>] <mcmc-results.png, id=39, 867.24pt x 578.16pt>
<use mcmc-results.png>

LaTeX Warning: Reference `fig:sheldon' on page 4 undefined on input line 178.

<compare-sheldon.png, id=40, 578.16pt x 433.62pt> <use compare-sheldon.png>
[4 <./inputs.png>] [5]
! Output routine didn't use all of \box255.
<argument> \@endparpenalty 

l.209 \end{thebibliography}

? 
(./maindoc.bbl)

Class revtex4-1 Warning: Environment {mathletters} is obsolete;
load the amsmath package and use {subequations}!.

[6](./maindoc.aux)

LaTeX Warning: There were undefined references.
"""

**Comment by davidwhogg** [comment]
I think you were supposed to open issues against me on reading / checking what's in this paper?

**Comment by aimalz** [comment]
Sorry, the paper in question was out of date.  An updated version is now in https://github.com/aimalz/prob-z/tree/master/minimal-nz, and I'll update it again shortly.  Note that the "methods" and "fake data" sections are more-or-less current, but the rest hasn't advanced in about a month.  In particular, the "introduction" is totally empty.  I'd really appreciate some references for the uses of N(z).

**Comment by davidwhogg** [comment]
make that N(z) request in a separate, correctly titled issue.

**Comment by davidwhogg** [comment]
there are no more warnings and etc, so I am closing this; open an issue on N(z)
