### ISSUE TITLE
how do I view a .ipynb file?

### ISSUE THREAD

**Issue by davidwhogg** [aimalz/prob-z#15]
@drphilmarshall how do I view a file like https://raw.githubusercontent.com/aimalz/prob-z/master/nz/minimal-profile.ipynb ?

**Comment by aimalz** [comment]
Does http://nbviewer.ipython.org/ not work?

**Comment by drphilmarshall** [comment]
You paste that URL into the form box at

http://nbviewer.ipython.org

The result is this page:

http://nbviewer.ipython.org/github/aimalz/prob-z/blob/master/nz/minimal-profile.ipynb

You can also just format that URL yourself, I believe.

**Comment by davidwhogg** [comment]
awesome!
