### ISSUE TITLE
what are the eigenvalues of the prior covariance?

### ISSUE THREAD

**Issue by davidwhogg** [aimalz/prob-z#18]
Please deliver as something pasted into this github issue.  I want them sorted from biggest to smallest!

**Comment by aimalz** [comment]
[7.6703120168776966,
 6.9506350235980605,
 5.899990569297751,
 4.6936058411641453,
 3.5017911547084952,
 2.4523765614082906,
 1.6138418731855819,
 0.99917266543092975,
 0.58277160702906305,
 0.32064330063371799,
 0.16664123843770551,
 0.081903346672069541,
 0.038109018391346464,
 0.016800258512729135,
 0.0070212808434896735,
 0.0027826992268280238,
 0.0010458859290801571,
 0.000372703491389753,
 0.00012585240115553791,
 4.0233470485002072e-05,
 1.2161370467669506e-05,
 3.4697101808731627e-06,
 9.3225626729557588e-07,
 2.3520340183834402e-07,
 5.5513904280797205e-08,
 1.2199524289988994e-08,
 2.4808702809028403e-09,
 4.6313431044324633e-10,
 7.8525954391461354e-11,
 1.1916399180030592e-11,
 1.5853935697637329e-12,
 1.7908754097151756e-13,
 1.6224172303993977e-14,
 7.3115946867051293e-16,
 9.9770946897606307e-17]

**Comment by davidwhogg** [comment]
Okay interesting.  Can you remind me of the parameters you used for this covariance?  Also, can you give me the same but for a lengthscale that is smaller by a factor of 2?

**Comment by davidwhogg** [comment]
also, can you do the same again, but adding to the diagonal 1e-6 \* Q (or whatever the amplitude parameter is called)?

**Comment by aimalz** [comment]
This covariance matrix C has C_ij = q_exp(-e_(i-j)^2/2) with q=1 and e=0.1.  
If e is halved, the eigenvalues don't change much : [10.547876746877691,
 8.7915032655079663,
 6.5006419407961555,
 4.2750936626653244,
 2.5093712534377439,
 1.3204644291267469,
 0.62605242035855935,
 0.26884481095895479,
 0.10510326312453344,
 0.037580831827134981,
 0.012339168708498324,
 0.0037326046325549278,
 0.0010430359541842512,
 0.00026980091665148681,
 6.4699713955275161e-05,
 1.4398289311410851e-05,
 2.9750070983177776e-06,
 5.707387873545954e-07,
 1.0161115730740204e-07,
 1.6770578409407432e-08,
 2.5618268691135671e-09,
 3.613707822220018e-10,
 4.6927854448240542e-11,
 5.5885210338950838e-12,
 6.0786829223806403e-13,
 5.9771764680791977e-14,
 4.3804798009631027e-15,
 1.8888406745306629e-15,
 8.2452300859630405e-16,
 5.421674189728721e-16,
 4.0057839267022917e-16,
 2.8314973249066514e-16,
 2.4670105107145218e-16,
 1.1234877347147369e-16,
 6.7914707971802022e-17]
If instead I use C_ij = q_exp(-e_(i-j)^2/2) + 1e-6*delta(i,j), the eigenvalues are more manageable without visibly affecting the appearance of samples from the prior: [7.6703130168776958,
 6.9506360235980598,
 5.8999915692977485,
 4.6936068411641445,
 3.5017921547084936,
 2.4523775614082903,
 1.6138428731855823,
 0.99917366543092856,
 0.58277260702906286,
 0.32064430063371807,
 0.16664223843770501,
 0.081904346672069542,
 0.038110018391346277,
 0.016801258512729532,
 0.0070222808434901541,
 0.0027836992268274918,
 0.001046885929080396,
 0.00037370349138968759,
 0.00012685240115570056,
 4.1233470484742057e-05,
 1.3161370468517308e-05,
 4.4697101806814946e-06,
 1.9322562674380431e-06,
 1.2352034017772141e-06,
 1.0555139041975564e-06,
 1.0121995244301153e-06,
 1.0024808701786699e-06,
 1.0004631342811991e-06,
 1.0000785255876203e-06,
 1.0000119162939488e-06,
 1.0000015852514321e-06,
 1.0000001786598488e-06,
 1.0000000159048873e-06,
 1.000000000131418e-06,
 1.0000000000258495e-06]
Note that these are computed using numpy, which calls the system linear algebra functions, so the results are somewhat different when computed on different operating systems.

**Comment by davidwhogg** [comment]
just for clarification, I want `tiny = 1.e-6 * q` not `1.e-6`.  Just make sure, and then close this issue.

**Comment by aimalz** [comment]
I've been using q=1.0, so that's already done.

**Comment by davidwhogg** [comment]
My point is just that the _code_ be written so that if you change q, you change tiny.
