### ISSUE TITLE
does emcee fail on 35-d pure Gaussian blob?

### ISSUE THREAD

**Issue by davidwhogg** [aimalz/prob-z#2]
@dfm, @aimalz do you two agree that emcee can't sample from a 35-d multivariate Gaussian in 4000 steps with 100 walkers?

If you do agree on this, what's our next step?

**Comment by dfm** [comment]
What do you mean by fail? The acceptance fraction goes down substantially
in high dimensions and the 1000 steps that @aimalz was showing yesterday
certainly weren't enough. This is a well know fact!

**Comment by davidwhogg** [comment]
what do we expect for the autocorrelation time for a 35-d Gaussian?

Also, @aimalz, how long did 1000 steps take?

**Comment by aimalz** [comment]
For all 35 dimensions, ![this](https://cloud.githubusercontent.com/assets/8606810/7203389/3f492f26-e4e8-11e4-9f06-e3ba5d20dfa9.png) is what the autocorrelation times look like.  1000 steps takes on the order of a minute for 35 dimensions.

**Comment by aimalz** [comment]
To test how well the sampler was working, I examined each walker's values of the parameters at each iteration for 10000 iterations.  The three rows are for the three initialization procedures (actual samples from the prior, the recommendation of @dfm, and the recommendation of @davidwhogg).
For 35 dimensions: 
![d35compare10000i](https://cloud.githubusercontent.com/assets/8606810/7211302/95a61980-e527-11e4-8f15-8c9c79f4a739.png)
For 18 dimensions: 
![d18compare10000i](https://cloud.githubusercontent.com/assets/8606810/7211303/9b27af7c-e527-11e4-8cc5-c1185bf8951e.png)
For 9 dimensions: 
![d9compare10000i](https://cloud.githubusercontent.com/assets/8606810/7211308/a131e5b8-e527-11e4-96eb-9d2094a35606.png)
As the number of dimensions increases, it takes longer before there are any samples spanning the distribution.  The acceptance ratios are ~1% for 35 parameters and <10% for half as many parameters.

**Comment by davidwhogg** [comment]
Okay this is all good and looks fine!

There was no guarantee that we would be able to fully MCMC sample in 1 minute!

So there is no problem at all.  Run the sampler for 1 hour and then 10 hours and make the same plots -- how does the autocorrelation time vary with number of samples up to, say, 10^5 or 10^6 samples?

Also, let's try running with just 80 walkers for efficiency.

**Comment by davidwhogg** [comment]
I am waiting on this -- can you show me the results for my request?

**Comment by aimalz** [comment]
what @davidwhogg wants to see is a plot of acceptance fraction (median) and autocorrelation time (median) as a function of number of dimensions, evaluated at 10, 15, 20, 25, 30, 35.

**Comment by aimalz** [comment]
At this point we've concluded that the failure was mostly my expectation of how long the burn-in period would be, so I'm closing this issue.
