### ISSUE TITLE
PGM needs updating

### ISSUE THREAD

**Issue by drphilmarshall** [aimalz/prob-z#25]
I used to be just the same, @aimalz - I tend to try and write down the probability theory first, and only then make the PGM! But these days I find it much easier to make a PGM first, and then turn it into math - and my experience so far has been that other astronomers much prefer PGMs to math too! :-)

**Comment by aimalz** [comment]
Good point!  I rearranged it to have the diagram and physical interpretation ahead of any math.  The paper's probably going to undergo some more reorganization before it's done, but I'll try to keep this in mind.

**Comment by aimalz** [comment]
Got it, am closing this ancient issue now.
