### ISSUE TITLE
don't check in zip files

### ISSUE THREAD

**Issue by davidwhogg** [aimalz/prob-z#26]
Not sure what's in the zip file in the code directory but it is huge!

Also, what's been added can't be unadded, so be careful.

**Comment by aimalz** [comment]
I think at some point you asked me to upload the output of one run of the code (though that was evidently not what you had in mind).  If absolutely necessary, there are sneaky ways to actually delete things from a repository.

**Comment by davidwhogg** [comment]
Yes, there are -- but let's not go there unless things get out of control.  From now on, let's not check in anything (data) that are generated by code

**Comment by aimalz** [comment]
Clearing out old issues -- I think I've learned my lesson here.
