### ISSUE TITLE
Autocorrelation Times

### ISSUE THREAD

**Issue by aimalz** [aimalz/prob-z#29]
Changing the window size on emcee's autocorrelation time calculator does not resolve the problem of uniformly zero autocorrelation times.  I need to find out what's wrong and fix it.

**Comment by aimalz** [comment]
The problem is that thinning the chain artificially independence-ifies adjacent samples, so the autocorrelation time between them really is that low.  The only way to fix it is to calculate autocorrelation times on an unthinned chain, which requires holding /a lot/ of samples in memory.

**Comment by aimalz** [comment]
Example of overthinned chain:

![chains](https://cloud.githubusercontent.com/assets/8606810/10460949/dba90910-71a4-11e5-8b63-d8ddf4be08ba.png)

Sample 2, Parameter 2 has an apparently negative autocorrelation time, but it's zero to within the system floating point precision.

**Comment by davidwhogg** [comment]
I don't understand how we can get _zero_.  I thought the minimum possible number is 1.  Can you give the formula for the autocorrelation time?

**Comment by davidwhogg** [comment]
ps.  If your chains are over-thinned, you are running MCMC for too long.

**Comment by aimalz** [comment]
I rewrote the autocorrelation calculator and no longer get times less than 1.  That's using post-thinned data, so whatever issues might have been at play with emcee's acor() function's failure shouldn't have vanished and are presumably actually resolved.  The results are comparable with what emcee gave when it was working.  I think the problem was that emcee didn't check that the maximum window size was sensible given the data, and I was giving it something that made no sense.

**Comment by davidwhogg** [comment]
Can you file a bug report against emcee on this?

**Comment by aimalz** [comment]
[Done](https://github.com/dfm/emcee/issues/171)
