### ISSUE TITLE
Improve accuracy and stability

### ISSUE THREAD

**Issue by aimalz** [aimalz/prob-z#30]
In the fiducial case, the variance and chi^2 are consistently higher than for the alternatives.  For the other test cases it varies per run, but they usually come out better than the alternatives by at least one of variance and chi^2 as measured from N(z) or ln[N(z)].
![samps](https://cloud.githubusercontent.com/assets/8606810/11125935/9001945c-893a-11e5-9bb2-98e167280ad9.png)
The log likelihood ratio is the only measure by which the fiducial case (and every other test) is consistently an improvement over the alternatives.
![llr](https://cloud.githubusercontent.com/assets/8606810/11126102/5ee14e34-893b-11e5-84ca-b5c4f377d27a.png)
The log posterior probabilities are sometimes lower for the accepted samples than they are for the stacking method, but sometimes they're higher as well.  In all test cases it varies for each run with different initial conditions, although the sampler outperforms the alternatives more often in the other tests than in the fiducial case.
![probs](https://cloud.githubusercontent.com/assets/8606810/11125977/c78ae216-893a-11e5-91cb-dc2f816af0a2.png)
I have some ideas for how to approach this problem but don't know what would be best.  I've thought about simply taking more samples by running it longer or using more walkers, but that doesn't seem supported by the log posterior probability evolution leveling off quite quickly and chi^2 and variance leveling off after the burn-in.  I've also thought about varying the prior used to generate initial values (and samples, to some extent?).  I can also try a different goodness of fit measure like the K-L divergence and see if it resolves the inconsistency issue.

**Comment by davidwhogg** [comment]
If you initialize the sampler at the end point of stacking the posteriors, then the sampler simply MUST go to a better place, right?  It can't get worse.  If it does, it is a bug.

**Comment by aimalz** [comment]
You're right, it does get better (going by the goodness of fit measures) if I use a prior with a mean equal to the stacked parameters and initialize based on that.  (At first I thought it didn't improve because the probability distribution I constructed for the KL divergence had an obviously wrong covariance structure; when I changed it to the same covariance as the prior, the log posterior probabilities, variance, and chi^2 started behaving more reasonably.)  I went back to plotting more samples because it's easier for me to see the distribution of parameter values compared to the true values:
![samps](https://cloud.githubusercontent.com/assets/8606810/11223828/e14b2194-8d3f-11e5-917d-5926cf1ee5c6.png)
However, I must still have bugs in at least some of my goodness of fit measures (chi^2 is stupidly low for the unlogged version of the parameters and the KLD is high for stacked vs. samples but zero for MAP and E(z) vs. sampled) and don't trust the quantification of the improvement.  I also get different results (in terms of the posterior probabilities of the samples versus that of the stacked posterior) for every run, which seems too inconsistent for me to claim any real improvement.

**Comment by aimalz** [comment]
I found my error with calculating the KLD, and it's a problem in my understanding rather than my implementation.  It is defined over the set of all possible parameter values, but I only have samples from that space.  Do you know how people normally calculate this when only samples are available?

**Comment by davidwhogg** [comment]
Not sure what you are asking.  If I give you two functions, p(z) and q(z), do you know how to compute 2 KLDs?

**Comment by aimalz** [comment]
Sorry, that was an ill-posed question brought to the world by Benadryl.  What I understand P and Q to be are the posterior probability distributions over the parameters theta.  The proof that the KLD is greater than zero depends on summing (integrating) over all possible values of theta rather than samples of that hyperparameter space.  I identified my KLD calculation as faulty based on getting negative and zero values, but those make sense given that I summed over samples of theta rather than all possible theta.  Does that make sense?  Because the output of the sampler is not a continuous distribution over hyperparameter space, I don't know what else I'd do to get the KLD as it should be, so I still have some kind of error in my thinking.

**Comment by davidwhogg** [comment]
If you have two functions p(z) and q(z), do you know what the KLD is between them?  There are two answers; we should compute both for any "answer" we get.  That could be a sample of p(z) or a "sum of posteriors" or whatever else we might report or anyone might report.

**Comment by aimalz** [comment]
I am aware that the KLD is defined as Sum_z (p(z) log[p(z)/q(z)]) or Sum_z (q(z) log[q(z)/p(z)]), both of which are valuable to compute because the KLD is affected differently by low values of p(z) and q(z).  I'm taking p(z) and q(z) to be posterior (or likelihood) distributions based on the sampled parameters (or competing methods) versus the distribution that produced the true parameters, i.e. z here is not redshift but rather the vector of parameter values I've been calling theta.  The sum, however, is not over sampled values of theta but instead over the entire space of possible values of theta, otherwise the KLD becomes uninterpretable.  To do a sum over the entire parameter space, I need a posterior distribution of the true parameters (and alternative parameter estimates) and have only just started thinking about the relevant explicit form(s), thanks to @ixkael.

**Comment by davidwhogg** [comment]
No, z should be redshift here.  Isn't the question:  How good is the redshift distribution?  I have lost track of what question is being asked!  Aren't we asking how good is an answer to the question "what is p(z)?"  If so, the answer is just the kld and z is redshift!

**Comment by aimalz** [comment]
How does the ratio of the parameter values (defining p(z)) tell us how good the fit is?  p and q must be either the likelihood or posterior distributions (they explicitly must be probabilities, not vectors of parameters), something involving the data, because that's the way we determine how good the fit is.

**Comment by davidwhogg** [comment]
I am still confused.  Don't we have a _True_ p(z) and we are trying to understand how good our estimate q(z) is of p(z)?  This comment thread is way too long!  I can't understand what it is that you are trying to measure.  Somehow there is a total failure to communicate.  Let's close this thread and why don't you write a section in the paper about how you intend to measure the goodness of fit, which is what I thought this was about.  Evidently this is not what this is about, because the goodness of fit is measured by the KLD between two redshift pdfs, the true one and the inferred one.  It's that simple, as far as I can tell.
