### ISSUE TITLE
Accuracy Tests

### ISSUE THREAD

**Issue by aimalz** [aimalz/prob-z#31]
This is a new issue for all matters related to accuracy tests.

**Comment by aimalz** [comment]
Results of the log likelihood ratio and KLD for a small test case:
![llr](https://cloud.githubusercontent.com/assets/8606810/11344400/0018bed0-91df-11e5-95b4-2f39f149fccd.png)

**Comment by ixkael** [comment]
Hi Alex, this looks interesting, could you please:
- clarify what I (and David) should be looking at and what we can conclude
- use more distinct linestyles and colours (I can't distinguish red and green)
- what do you call a small test case?
  Thanks!

**Comment by aimalz** [comment]
The plot on the left shows the log likelihood ratios for each method relative to the samples.  A value greater than zero indicates the samples have a higher likelihood than the alternative methods.  The maximum value seems to be used as the measure of how good a fit the samples are relative to the competing methods so I included that information.  Based on the maximum values the sampler does better than the alternatives but the mean/median/mode of the distribution of log likelihood ratios would indicate they're comparable. 

The plot on the right shows the KLD, with a KDE of the samples and the values for the point estimates.  A lower value means the estimator is closer to the true value.  To be optimistic, I also printed the minimum value.  Again, the minimum values say the sampler is better than the alternatives but the mean/median/mode of the KLD would say otherwise.

Re: colors: To my knowledge matplotlib only permits four line styles, so we'll have to make do.  I'll use a different set of colors in the future.

Re: small test case: I ran a test of 100 galaxies just so I could verify that my KLD calculator worked; I'm running it for 1000 galaxies now but wanted to post something immediately.

**Comment by davidwhogg** [comment]
I have no idea what you are plotting.  If you run a method (say, adding up the posteriors), you get a p(z).  That p(z) has a KLD against the truth.  This KLD is a scalar number that is not a function of anything.  It doesn't appear on a plot.  It is just a number.

Also, never make plots without axis labels.  The plot on the right shows the KLD vs WHAT?  The KLD doesn't depend on anything so I don't see what it could be plotted against. 

Also the phrase "log likelihood ratios for each method relative to the samples" makes no sense to me.

What I want, is for each method you create to output a p(z), and a KLD for that p(z).  That is, a function of z and a scalar.  Again, we are off the rails.  Let's start with TWO METHODs:
- Add up posteriors (known to be wrong).  Get p(z) from that.  Compute KLD.
- Histogram the ML redshift values (known to be less wrong).  Get p(z) from that binning.  Compute KLD.

Which is better?  Forget the inference and the sampling and everything.  Just demonstrate that we can compare two p(z) results with some metric!

**Comment by davidwhogg** [comment]
ps.  I think the name "goodness of fit" is a misnomer.  We are trying to understand how close we are to the Truth, not how well we fit the data, which will be a separate question (which we might not answer at all in paper 1).

**Comment by ixkael** [comment]
Hi both,

I agree with David: let's first check that the KLD calculations are correct and that we are all on the same page. I would even start with a couple of simpler examples, i.e. KLD between two gaussians, and check that the analytic and numerical values of the KLD agree. Then computing the KLD for the stacked P(z) and histogram of ML values should be next. I agree that it is worth forgetting about the inference and sampling at present to debug the KLD.

Boris

**Comment by aimalz** [comment]
The plots have been updated, sorry about the lack of labels.

The log likelihood ratios are computed between individual parameter values, so there's one per sample per alternative.  Because there are many samples produced by our approach and reduction to a point estimate would be inappropriate and unfavorable, we end up with a distribution of log likelihood ratios, plotted as a KDE rather than a histogram for arbitrary reasons.

The KLD is a scalar number per set of parameters we're comparing to the truth.  The sampler produces thousands of these, with some distribution of KLDs, plotted again as a KDE.  The KLD values for the truth vs. stacking/MAP/E(z) are also shown as vertical lines, with a thin line and a thick line for each "direction" since the KLD is not symmetric.

**Comment by davidwhogg** [comment]
I _still_ don't understand.  Can you give me the KLD for _one_ sample?  Or the histogram of KLDs for a set of samples?  And compare to the KLD for the sum of posteriors (which should be worse) and the KLD for the histogram of ML redshift values (which also should be worse).   And you can also give the KLD for the mean of posterior samples and for the maximum-marginalized likelihood.  Right?

Also, I don't see how you have two-d plots with lines on them.  If they are the values you get from samples, shouldn't they be scatter plots, not lines?  I am just so confused.

**Comment by davidwhogg** [comment]
I am going to open YET ANOTHER ISSUE on this.

**Comment by davidwhogg** [comment]
Finally:  I don't like the units / magnitude of your KLD.  Doesn't look right; answers of 0.01 or 0.1 are very hard to get:  They imply distributions that are almost indistinguishable.

**Comment by aimalz** [comment]
I wasn't aware of the usual scope of KLDs -- that is troubling.  I mentioned it [elsewhere](https://github.com/aimalz/prob-z/issues/34) but they're sensitive to using N(z) vs. p(z), even though the difference should just be a scaling under which KLD ought to be invariant.  The definition of KLD does specify that p(z) be used instead of N(z), and that's what gives the strangely low values.  In any case, they do pass the test of getting much smaller for nearly identical N(z)s and larger for those that are more different; see the KLD for underlying N(z) vs. truth below, where it's 0 to within floating point precision.
![truenz](https://cloud.githubusercontent.com/assets/8606810/11350066/b635ca28-91fd-11e5-913c-d0d884e2d7a4.png)

**Comment by davidwhogg** [comment]
This looks closer, but

(a) What is the difference between "true" and "underlying"?

(b) If I can see a difference between "true" and "underlying" then the KLD can't be 1e-15.

(c) The KLD must be done on p(z) not N(z) -- so normalize first and do that.

(d) What are you using as your KLD formula?  Give it to me exactly and point me to code.

(e) What is the MAP histogram plotting?  Be specific.  It is the output of what operation?

(f) What is the N(E(z))?  Same question.

**Comment by aimalz** [comment]
a) "Underlying" is the physically-motivated N(z) shape from which a sample is drawn for what the data will be, normalized to the expected survey size.  "True" is what was sampled (observed survey size equal to Poisson random variable about expected survey size, bin heights determined by random sample of the probabilities defined by the underlying distribution).  Does that make sense?  I describe this with equations in the paper.

b) I'm not sure what's up with the scaling, but the relative KLDs (stacked to truth vs. underlying to truth) are on the order of what I'd expect.  I found a bug in the normalization (accidentally divided by bin widths instead of multiplying when normalizing ln[N(z)] to p(z), yikes!), so that should fix it.  I'm running a test now. EDIT: That only makes the problem worse.  I'm investigating.

c) Indeed! 

d) KLD = sum_k p(z_k) \* (ln[p(z_k)] - ln[q(z_k)])  It's at line 315 of https://github.com/aimalz/prob-z/blob/master/nz/code/mcmc/statmcmc.py.

e) The MAP histogram is N(z) where z is a point estimate of redshift equal to the center of the bin where the zPDF is maximized.

f) N(E(z)) is N(z) where z is a point estimate of redshift equal to the expected value of redshift for each galaxy based on its zPDF.

**Comment by davidwhogg** [comment]
(a) okay

(b) figure it out.  Try simple cases.

(c) good fix this everywhere.

(d) wrong formula.  there needs to be a delta-z in there.  It is an integral, right?

(e) Okay

(f) Okay, but let's drop this case for now (and probably forever) since no-one would ever do this.

**Comment by aimalz** [comment]
b) I've been playing with it all day without resolution (yet).  The KLD is supposed to be invariant under changes of variables, so I don't see how a scaling (that is lost when N(z) is converted into p(z) or p(B), for redshift bin B) can make any difference, but it does.  I'll update this issue when I figure it out.

d) So there's a formula for a continuous p(z) and a formula for a discrete p(B).  In this simple case, it's easy to convert between them as p(B)=int_B p(z) dz.  The bottom line is that int p(z) dz must equal 1 if it's continuous and sum_k p(B_k) must equal 1 if it's discrete, and I have checked that this holds for either way that I calculate it.  I get the exact same KLD regardless of whether I use the continuous or discrete forms of the probability distribution, and that is expected behavior.

f) I left it in because it often does better than stacking.  If people would balk at using E(z), they should be even more discouraged from stacking.  I can take it out if you think that point wouldn't persuade the broader community.

**Comment by davidwhogg** [comment]
On (b) it is a transformation of the _argument_ of p(z) that it is invariant to.

On (d) good!  Yes, your normalization conditions must be consistent.  Just be consistent.  But my view is that z is really continuous and we have a step function, NOT a set of discrete values for z.  I would prefer this because it is a better approximation to the real world.

On (f) But so does the MAP values, right?  So that makes the point just as well.
