### ISSUE TITLE
show me the p(z) for a galaxy that has z_obs outside the z_true range

### ISSUE THREAD

**Issue by davidwhogg** [aimalz/prob-z#36]

**Comment by aimalz** [comment]
This is an example from the multimodal test case.  The dashed lines are the true redshifts and the dotted lines are {z_obs} (where there are multiple z_obs for some galaxies).
![samplepzs](https://cloud.githubusercontent.com/assets/8606810/11594146/5e923ece-9a76-11e5-9efb-dcbca25b0fda.png)

**Comment by davidwhogg** [comment]
None of these is problematic, is it?  There are no bad edge effects visible there, are there?

Do those sigma-z values make sense?  These are pretty bad photo-zs!  Much worse than we expect, no?

**Comment by aimalz** [comment]
Yes, these are definitely worse than what would be expected for real data.  I've experimented with other formulations but never settled on a physically motivated way to modify the standard deviations of the Gaussian components.

**Comment by davidwhogg** [comment]
Let's verify all code and then return to that issue.
