### ISSUE TITLE
paper seems to be about likelihoods

### ISSUE THREAD

**Issue by davidwhogg** [aimalz/prob-z#7]
I thought you said that the paper took as inputs posterior pdfs on z, not likelihoods.  I don't see that; can you point me?

**Comment by aimalz** [comment]
My work took likelihoods as input, but others produce and use posteriors.  Sorry for the confusion.

**Comment by davidwhogg** [comment]
Okay, when you make the conversion to a N(z) document, also switch to posterior inputs

**Comment by aimalz** [comment]
I believe what you're looking for is the "probabilistic model" section of the document in https://github.com/aimalz/prob-z/tree/master/nz.

**Comment by davidwhogg** [comment]
Equation (3) is all wrong!

Number _all_ equations for now.

The chain from (2) to (3) has some mistakes in it.  Consult the following for advice about manipulating expressions:

http://arxiv.org/abs/1205.4446

And we are NOT trying to get p(d | N)!  We have decided that we _can't_ have likelihoods.  We are trying to get p(N|d) given a set of inputs that are p(z|d, N_0)

**Comment by aimalz** [comment]
I updated the probabilistic model section of the paper in accordance with our discussion on Tuesday.

**Comment by davidwhogg** [comment]
assigning myself to check this

**Comment by aimalz** [comment]
I incorporated the changes indicated on the printed version of my paper when I last commented.  How does it look?
