### ISSUE TITLE
Visibility: README, plots in notebooks

### ISSUE THREAD

**Issue by drphilmarshall** [aimalz/prob-z#8]
Hi Alex! Just checking in. Looks like this project is coming along :-) One thing that will help me follow your progress is a README file with some brief introduction to the project and what you are currently focused on. This is really helpful to let other people know what you are working on, so they can cite you! 

In that README you should post a link to your notebook, displayed in nbviewer. [Check this out.](http://nbviewer.ipython.org/github/aimalz/prob-z/blob/master/pz-demo.ipynb) I notice that your plots don't show up in that notebook - you can fix this by adding something like 

```
%matplotlib inline
```

at the top, with the import statements.

**Comment by davidwhogg** [comment]
@aimalz do make this matplotlib inline change and then you can send me a link to an nbviewer display of your notebook when you want to show me a result.

**Comment by aimalz** [comment]
@drphilmarshall Sorry I haven't updated this repository in far too long.  I've been using inline plots for some time now, and the working-doc directory had something like a readme, although it's sufficiently out of date to merit replacement.  Stay tuned for a revision of that later today.

**Comment by drphilmarshall** [comment]
Ah, sorry! I assume all github repos are fully pushe at all times :-)

**Comment by davidwhogg** [comment]
@aimalz you should push any day that you make any changes.

**Comment by aimalz** [comment]
I've added a small readme to the repository.

**Comment by davidwhogg** [comment]
good one
